spring.application.name=ToDoListApplication

#DB
spring.datasource.url=jdbc:postgresql://localhost:5432/exampleDB
spring.datasource.username=postgres
spring.datasource.password=123
#Hibernate
spring.jpa.hibernate.ddl-auto=create

# hikari CP
spring.datasource.hikari.maximum-pool-size=8

